const ChannelHeaderIcon = () => {
    return (
        <svg
            width='24'
            height='24'
            viewBox='0 0 24 24'
            xmlns='http://www.w3.org/2000/svg'
            aria-hidden='true'
            focusable='false'
        >
            <circle
                cx='12'
                cy='12'
                r='12'
                fill='#FFFFFF'
            />
            <rect
                x='8.5'
                y='3.5'
                width='1.6'
                height='4'
                rx='0.8'
                fill='#4285F4'
            />
            <rect
                x='13.9'
                y='3.5'
                width='1.6'
                height='4'
                rx='0.8'
                fill='#4285F4'
            />
            <rect
                x='6'
                y='5'
                width='12'
                height='14'
                rx='2'
                fill='#4285F4'
                fillOpacity='0.12'
            />
            <path
                d='M6 5h12a2 2 0 012 2v2H4V7a2 2 0 012-2z'
                fill='#4285F4'
            />
            <rect
                x='8'
                y='12'
                width='2'
                height='2'
                rx='0.4'
                fill='#4285F4'
            />
            <rect
                x='11'
                y='12'
                width='2'
                height='2'
                rx='0.4'
                fill='#4285F4'
            />
            <rect
                x='14'
                y='12'
                width='2'
                height='2'
                rx='0.4'
                fill='#4285F4'
            />
            <rect
                x='8'
                y='15'
                width='2'
                height='2'
                rx='0.4'
                fill='#4285F4'
            />
            <rect
                x='11'
                y='15'
                width='2'
                height='2'
                rx='0.4'
                fill='#4285F4'
            />
        </svg>
    );
};

export default ChannelHeaderIcon;
